from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_DIR = SCRIPT_DIR / "outputs"
DEFAULT_INPUT_CSV = DEFAULT_OUTPUT_DIR / "era_kb_scalability.csv"
DEFAULT_OUTPUT_PDF = DEFAULT_OUTPUT_DIR / "era_kb_scalability_dual_axis.pdf"
DEFAULT_OUTPUT_PNG = DEFAULT_OUTPUT_DIR / "era_kb_scalability_dual_axis.png"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot dual-axis ERA knowledge-bank scalability figure from a CSV."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=DEFAULT_INPUT_CSV,
        help="CSV generated by benchmark_kb_scalability.py",
    )
    parser.add_argument(
        "--output-pdf",
        type=Path,
        default=DEFAULT_OUTPUT_PDF,
        help="Destination PDF figure.",
    )
    parser.add_argument(
        "--output-png",
        type=Path,
        default=DEFAULT_OUTPUT_PNG,
        help="Destination PNG figure.",
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    args = parse_args()
    rows = load_rows(args.input_csv)
    if not rows:
        raise ValueError(f"No rows found in {args.input_csv}")

    bank_sizes = [int(row["bank_size"]) for row in rows]
    latency_mean = [float(row["latency_mean_ms"]) for row in rows]
    latency_p95 = [float(row["latency_p95_ms"]) for row in rows]
    memory_mb = [float(row["payload_memory_mb"]) for row in rows]
    labels = [row["checkpoint_label"] for row in rows]
    latent_dim = int(rows[0]["latent_space_dimensions"])
    device = rows[0]["benchmark_device"]

    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": 13,
            "axes.labelsize": 12,
            "legend.fontsize": 10,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
        }
    )

    fig, ax1 = plt.subplots(figsize=(8.6, 5.0))
    ax2 = ax1.twinx()

    latency_line = ax1.plot(
        bank_sizes,
        latency_mean,
        color="#0B6E4F",
        marker="o",
        linewidth=2.2,
        label="Mean retrieval latency",
    )[0]
    p95_line = ax1.plot(
        bank_sizes,
        latency_p95,
        color="#4C956C",
        marker="s",
        linewidth=1.6,
        linestyle="--",
        label="P95 retrieval latency",
    )[0]
    memory_line = ax2.plot(
        bank_sizes,
        memory_mb,
        color="#C75146",
        marker="D",
        linewidth=2.2,
        label="Memory footprint",
    )[0]

    ax1.set_xlabel("Knowledge Bank Size (entries)")
    ax1.set_ylabel("Retrieval Latency (ms)", color="#0B6E4F")
    ax2.set_ylabel("Memory Footprint (MB)", color="#C75146")
    ax1.tick_params(axis="y", colors="#0B6E4F")
    ax2.tick_params(axis="y", colors="#C75146")
    ax1.grid(alpha=0.25, linestyle=":")

    ax1.set_title(
        f"ERA Knowledge Bank Scalability ({latent_dim}-D event-centric latent code, device={device})"
    )

    for x, y, label in zip(bank_sizes, latency_mean, labels):
        ax1.annotate(label, (x, y), textcoords="offset points", xytext=(0, 7), ha="center", fontsize=8)

    takeaway = (
        f"{bank_sizes[0]:,} -> {bank_sizes[-1]:,} entries\n"
        f"latency {latency_mean[0]:.3f} -> {latency_mean[-1]:.3f} ms\n"
        f"memory {memory_mb[0]:.2f} -> {memory_mb[-1]:.2f} MB"
    )
    ax1.text(
        0.02,
        0.98,
        takeaway,
        transform=ax1.transAxes,
        va="top",
        ha="left",
        fontsize=9,
        bbox={"boxstyle": "round,pad=0.35", "facecolor": "white", "alpha": 0.9, "edgecolor": "#999999"},
    )

    handles = [latency_line, p95_line, memory_line]
    labels = [handle.get_label() for handle in handles]
    ax1.legend(handles, labels, loc="lower right", frameon=True)

    fig.tight_layout()
    args.output_pdf.parent.mkdir(parents=True, exist_ok=True)
    args.output_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output_pdf, dpi=300, bbox_inches="tight")
    fig.savefig(args.output_png, dpi=300, bbox_inches="tight")
    print(f"[saved] PDF -> {args.output_pdf}")
    print(f"[saved] PNG -> {args.output_png}")


if __name__ == "__main__":
    main()
